/**
 * @flow
 */

import React from 'react';
import { ScrollView, View, StyleSheet } from 'react-native';
import SettingsNavBar from '../component/SettingsNavBar';
import SettingsSectionHeader from '../component/SettingsSectionHeader';
import SettingsButton from '../component/SettingsButton';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#EEEEEE',
  },
  padding: {
    height: 40,
    backgroundColor: '#2c3e50'
  }
});

export default class SettingsScene extends React.Component<Props, State> {
  // This ensures that the view will be re-rendered on changes of orientation,
  // but forces one unnecessarily update upon the first rendering
  onLayout() {
    this.forceUpdate();
  }

  render() {
    return (
      <ScrollView
        style={styles.container}
        onLayout={this.onLayout.bind(this)}
      >
        <View style={styles.padding} />
        <SettingsNavBar />
        <SettingsSectionHeader
          title='Interface'
        />
        <SettingsButton
          title='Toggle with short press'
          description='Put checkmarks with a single tap instead of  press-and-hold. More convenient, but may cause accidental toggles.'
          checked={false}
        />
        <SettingsButton
          title='Reverse order of days'
          description='Show days in reverse order on the main screen.'
          checked={false}
        />
        <SettingsButton
          title='User pure black in night mode'
          description='Replaces gray backgrounds with pure black in night mode. Reduces battery usage in phones with AMOLED display.'
          checked={false}
          showBottomBorder={false}
        />
        <SettingsSectionHeader
          title='Reminder'
        />
        <SettingsButton
          title='Make notifications sticky'
          description='Prevents notifications from being swiped away.'
        />
        <SettingsButton
          title='Customize notifications'
          description='Change sound, vibration, light, and other notification settings.'
          showBottomBorder={false}
        />
        <SettingsSectionHeader
          title='Database'
        />
        <SettingsButton
          title='Export full backup'
          description='Generates a file that contains all your data. This file can be imported back.'
        />
        <SettingsButton
          title='Export as CSV'
          description='Generates files that can be opened by spreadsheet software such as Microsoft Excel or OpenOffice Calc. This file cannot be imported back.'
        />
        <SettingsButton
          title='Import data'
          description='Supports full backups exported by this app, as well as files generated by Tickmate, HabitBull or Rewrite. See FAW for more information.'
          showBottomBorder={false}
        />
        <SettingsSectionHeader
          title='Troubleshooting'
        />
        <SettingsButton
          title='Generate bug report'
        />
        <SettingsButton
          title='Repair database'
          showBottomBorder={false}
        />
        <SettingsSectionHeader
          title='Links'
        />
        <SettingsButton
          title='Help & FAQ'
        />
        <SettingsButton
          title='Rate this app'
        />
        <SettingsButton
          title='About'
          showBottomBorder={false}
        />
      </ScrollView>
    );
  }
}
